"""create hiu_consents

Revision ID: b3c4d5e6f7a8
Revises: a2b3c4d5e6f7
Create Date: 2026-09-07

repo/'s Postgres-backed replacement for storage/hiu_consents.jsonl --
fully-fetched consent artefacts WE, acting as an HIU, obtained via a real
on-fetch callback for a request THIS registration itself raised. This is
the table the "no cross-registration consent reuse" security property
rests on -- see server/callbacks/repository/hiu_consent_repository.py's
own banner before changing anything about how rows land here. See also
server/db_models.py:HiuConsent. Written by hand rather than autogenerated
so the JSONB and timestamptz choices are explicit, same convention as
aegle-phr/alembic/versions/*.py.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "b3c4d5e6f7a8"
down_revision: Union[str, None] = "a2b3c4d5e6f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "hiu_consents",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("consent_id", sa.Text(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_hiu_consents"),
        sa.UniqueConstraint("consent_id", name="uq_hiu_consents_consent_id"),
    )


def downgrade() -> None:
    op.drop_table("hiu_consents")
