"""create consents

Revision ID: a2b3c4d5e6f7
Revises: f1e2d3c4b5a6
Create Date: 2026-09-07

repo/'s Postgres-backed replacement for storage/consents.jsonl -- consents
WE, as an HIP, received notification of. See
server/callbacks/repository/consent_repository.py and
server/db_models.py:Consent. Written by hand rather than autogenerated so
the JSONB and timestamptz choices are explicit, same convention as
aegle-phr/alembic/versions/*.py.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "a2b3c4d5e6f7"
down_revision: Union[str, None] = "f1e2d3c4b5a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "consents",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("consent_id", sa.Text(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_consents"),
        sa.UniqueConstraint("consent_id", name="uq_consents_consent_id"),
    )


def downgrade() -> None:
    op.drop_table("consents")
