"""create dummy emr tables

Revision ID: 088dbda4c9bd
Revises: a4b5c6d7e8f9
Create Date: 2026-09-07 12:54:32.211713+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '088dbda4c9bd'
down_revision: Union[str, None] = 'a4b5c6d7e8f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('hip_id', sa.Text(), nullable=False),
    sa.Column('organization_name', sa.Text(), nullable=False),
    sa.Column('organization_type', sa.Text(), nullable=False),
    sa.Column('address_line1', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('pincode', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('hip_id')
    )
    op.create_table('patients',
    sa.Column('patient_reference', sa.Text(), nullable=False),
    sa.Column('abha_address', sa.Text(), nullable=False),
    sa.Column('abha_number', sa.Text(), nullable=True),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('gender', sa.Text(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('mobile', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('blood_group', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('patient_reference')
    )
    op.create_table('practitioners',
    sa.Column('practitioner_reference', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('speciality', sa.Text(), nullable=True),
    sa.Column('qualification', sa.Text(), nullable=True),
    sa.Column('registration_number', sa.Text(), nullable=True),
    sa.Column('registration_system', sa.Text(), nullable=True),
    sa.Column('mobile', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('practitioner_reference')
    )
    op.create_table('encounters',
    sa.Column('encounter_reference', sa.Text(), nullable=False),
    sa.Column('facility_encounter_number', sa.Text(), nullable=True),
    sa.Column('hip_id', sa.Text(), nullable=False),
    sa.Column('patient_reference', sa.Text(), nullable=False),
    sa.Column('practitioner_reference', sa.Text(), nullable=True),
    sa.Column('mr_number', sa.Text(), nullable=True),
    sa.Column('encounter_datetime', sa.DateTime(), nullable=True),
    sa.Column('encounter_type', sa.Text(), nullable=True),
    sa.Column('visit_reason', sa.Text(), nullable=True),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('encounter_status', sa.Text(), nullable=True),
    sa.Column('department_reference', sa.Text(), nullable=True),
    sa.Column('clinical_case', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['hip_id'], ['organizations.hip_id'], ),
    sa.ForeignKeyConstraint(['patient_reference'], ['patients.patient_reference'], ),
    sa.ForeignKeyConstraint(['practitioner_reference'], ['practitioners.practitioner_reference'], ),
    sa.PrimaryKeyConstraint('encounter_reference')
    )
    op.create_table('practitioner_organizations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('practitioner_reference', sa.Text(), nullable=False),
    sa.Column('hip_id', sa.Text(), nullable=False),
    sa.Column('department', sa.Text(), nullable=True),
    sa.Column('designation', sa.Text(), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['hip_id'], ['organizations.hip_id'], ),
    sa.ForeignKeyConstraint(['practitioner_reference'], ['practitioners.practitioner_reference'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('practitioner_reference', 'hip_id', name='uq_practitioner_organizations_practitioner_hip')
    )
    op.create_table('billing',
    sa.Column('invoice_reference', sa.Text(), nullable=False),
    sa.Column('encounter_reference', sa.Text(), nullable=False),
    sa.Column('patient_reference', sa.Text(), nullable=False),
    sa.Column('hip_id', sa.Text(), nullable=False),
    sa.Column('consultation_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pharmacy_charge', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('investigation_charge', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('procedure_charge', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['encounter_reference'], ['encounters.encounter_reference'], ),
    sa.ForeignKeyConstraint(['hip_id'], ['organizations.hip_id'], ),
    sa.ForeignKeyConstraint(['patient_reference'], ['patients.patient_reference'], ),
    sa.PrimaryKeyConstraint('invoice_reference')
    )
    op.create_table('conditions',
    sa.Column('condition_reference', sa.Text(), nullable=False),
    sa.Column('encounter_reference', sa.Text(), nullable=False),
    sa.Column('patient_reference', sa.Text(), nullable=False),
    sa.Column('clinical_case', sa.Text(), nullable=True),
    sa.Column('diagnosis_reference', sa.Text(), nullable=True),
    sa.Column('condition_name', sa.Text(), nullable=True),
    sa.Column('icd10_code', sa.Text(), nullable=True),
    sa.Column('snomed_code', sa.Text(), nullable=True),
    sa.Column('chronic', sa.Boolean(), nullable=True),
    sa.Column('severity', sa.Text(), nullable=True),
    sa.Column('clinical_status', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.Text(), nullable=True),
    sa.Column('onset_date', sa.Date(), nullable=True),
    sa.Column('recorded_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['encounter_reference'], ['encounters.encounter_reference'], ),
    sa.ForeignKeyConstraint(['patient_reference'], ['patients.patient_reference'], ),
    sa.PrimaryKeyConstraint('condition_reference')
    )
    op.create_table('diagnostic_reports',
    sa.Column('diagnostic_report_reference', sa.Text(), nullable=False),
    sa.Column('encounter_reference', sa.Text(), nullable=False),
    sa.Column('patient_reference', sa.Text(), nullable=False),
    sa.Column('lab_reference', sa.Text(), nullable=True),
    sa.Column('test_name', sa.Text(), nullable=True),
    sa.Column('loinc', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('result_value', sa.Text(), nullable=True),
    sa.Column('reference_range', sa.Text(), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('interpretation', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('issued_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['encounter_reference'], ['encounters.encounter_reference'], ),
    sa.ForeignKeyConstraint(['patient_reference'], ['patients.patient_reference'], ),
    sa.PrimaryKeyConstraint('diagnostic_report_reference')
    )
    op.create_table('documents',
    sa.Column('document_reference', sa.Text(), nullable=False),
    sa.Column('encounter_reference', sa.Text(), nullable=False),
    sa.Column('patient_reference', sa.Text(), nullable=False),
    sa.Column('document_type', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('authored_datetime', sa.DateTime(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('content_type', sa.Text(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['encounter_reference'], ['encounters.encounter_reference'], ),
    sa.ForeignKeyConstraint(['patient_reference'], ['patients.patient_reference'], ),
    sa.PrimaryKeyConstraint('document_reference')
    )
    op.create_table('immunizations',
    sa.Column('immunization_reference', sa.Text(), nullable=False),
    sa.Column('encounter_reference', sa.Text(), nullable=False),
    sa.Column('patient_reference', sa.Text(), nullable=False),
    sa.Column('vaccine_reference', sa.Text(), nullable=True),
    sa.Column('vaccine_name', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('occurrence_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['encounter_reference'], ['encounters.encounter_reference'], ),
    sa.ForeignKeyConstraint(['patient_reference'], ['patients.patient_reference'], ),
    sa.PrimaryKeyConstraint('immunization_reference')
    )
    op.create_table('medication_requests',
    sa.Column('medication_request_reference', sa.Text(), nullable=False),
    sa.Column('encounter_reference', sa.Text(), nullable=False),
    sa.Column('patient_reference', sa.Text(), nullable=False),
    sa.Column('medication_reference', sa.Text(), nullable=True),
    sa.Column('generic_name', sa.Text(), nullable=True),
    sa.Column('brand_name', sa.Text(), nullable=True),
    sa.Column('strength', sa.Text(), nullable=True),
    sa.Column('atc_code', sa.Text(), nullable=True),
    sa.Column('dosage_form', sa.Text(), nullable=True),
    sa.Column('route', sa.Text(), nullable=True),
    sa.Column('frequency', sa.Text(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('authored_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['encounter_reference'], ['encounters.encounter_reference'], ),
    sa.ForeignKeyConstraint(['patient_reference'], ['patients.patient_reference'], ),
    sa.PrimaryKeyConstraint('medication_request_reference')
    )
    op.create_table('observations',
    sa.Column('observation_reference', sa.Text(), nullable=False),
    sa.Column('encounter_reference', sa.Text(), nullable=False),
    sa.Column('patient_reference', sa.Text(), nullable=False),
    sa.Column('observation_master_reference', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('loinc', sa.Text(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('effective_datetime', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['encounter_reference'], ['encounters.encounter_reference'], ),
    sa.ForeignKeyConstraint(['patient_reference'], ['patients.patient_reference'], ),
    sa.PrimaryKeyConstraint('observation_reference')
    )
    op.create_table('patient_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('abha_address', sa.Text(), nullable=True),
    sa.Column('abha_number', sa.Text(), nullable=True),
    sa.Column('mobile', sa.Text(), nullable=True),
    sa.Column('mr_number', sa.Text(), nullable=True),
    sa.Column('facility_id', sa.Text(), nullable=False),
    sa.Column('patient_reference', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('care_context_reference', sa.Text(), nullable=False),
    sa.Column('care_context_display', sa.Text(), nullable=True),
    sa.Column('hi_type', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['care_context_reference'], ['encounters.encounter_reference'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['organizations.hip_id'], ),
    sa.ForeignKeyConstraint(['patient_reference'], ['patients.patient_reference'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('care_context_reference', 'hi_type', name='uq_patient_records_care_context_hi_type')
    )
    op.create_table('procedures',
    sa.Column('procedure_reference', sa.Text(), nullable=False),
    sa.Column('encounter_reference', sa.Text(), nullable=False),
    sa.Column('patient_reference', sa.Text(), nullable=False),
    sa.Column('procedure_master_reference', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('performed_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['encounter_reference'], ['encounters.encounter_reference'], ),
    sa.ForeignKeyConstraint(['patient_reference'], ['patients.patient_reference'], ),
    sa.PrimaryKeyConstraint('procedure_reference')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('procedures')
    op.drop_table('patient_records')
    op.drop_table('observations')
    op.drop_table('medication_requests')
    op.drop_table('immunizations')
    op.drop_table('documents')
    op.drop_table('diagnostic_reports')
    op.drop_table('conditions')
    op.drop_table('billing')
    op.drop_table('practitioner_organizations')
    op.drop_table('encounters')
    op.drop_table('practitioners')
    op.drop_table('patients')
    op.drop_table('organizations')
    # ### end Alembic commands ###
