"""create patient_identities

Revision ID: f1e2d3c4b5a6
Revises:
Create Date: 2026-09-07

repo/'s Postgres-backed replacement for storage/patient_identities.jsonl --
see server/callbacks/repository/patient_identity_repository.py and
server/db_models.py:PatientIdentity. Written by hand rather than
autogenerated so the JSONB and timestamptz choices are explicit, same
convention as aegle-phr/alembic/versions/*.py.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "f1e2d3c4b5a6"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "patient_identities",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("abha_address", sa.Text(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_patient_identities"),
        sa.UniqueConstraint("abha_address", name="uq_patient_identities_abha_address"),
    )


def downgrade() -> None:
    op.drop_table("patient_identities")
