"""
Clinical Case Library.

Single source of truth for every downstream dummy-EMR generator.
Each case is anchored to a diagnosis_reference in the diagnoses master
(tools/dummy_emr/master_data/diagnoses/) rather than duplicating
condition name/ICD-10/SNOMED data inline.
"""

CLINICAL_CASES = [
    {
        "case_id": "CASE001",
        "name": "Essential Hypertension",
        "department_reference": "DEP001",
        "specialty_reference": "SP001",
        "diagnosis_reference": "DXGM001",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Headache and occasional dizziness",
        },
        "clinical_history": "Diagnosed hypertensive, here for routine follow-up",
        "medication_references": ['MED000002', 'MED000003'],
        "observation_references": ['OBS000001', 'OBS000002'],
        "lab_references": ['LAB000005'],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription', 'Invoice'],
        "billing_profile": "General Medicine",
        "follow_up_interval_days": 30,
        "selection_weight": 8,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'Observation', 'DiagnosticReport', 'DocumentReference'],
    },

    {
        "case_id": "CASE002",
        "name": "Type 2 Diabetes Mellitus",
        "department_reference": "DEP001",
        "specialty_reference": "SP001",
        "diagnosis_reference": "DXGM002",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Increased thirst and frequent urination",
        },
        "clinical_history": "Known diabetic on oral hypoglycemics, routine review",
        "medication_references": ['MED000004'],
        "observation_references": ['OBS000001', 'OBS000007'],
        "lab_references": ['LAB000002', 'LAB000006'],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription', 'Diagnostic Report'],
        "billing_profile": "General Medicine",
        "follow_up_interval_days": 90,
        "selection_weight": 8,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'Observation', 'DiagnosticReport', 'DocumentReference'],
    },

    {
        "case_id": "CASE003",
        "name": "Acute Viral Fever",
        "department_reference": "DEP001",
        "specialty_reference": "SP001",
        "diagnosis_reference": "DXGM003",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Fever with body ache for 3 days",
        },
        "clinical_history": "Acute febrile illness, no red flag symptoms",
        "medication_references": ['MED000001'],
        "observation_references": ['OBS000004', 'OBS000002'],
        "lab_references": ['LAB000001'],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription'],
        "billing_profile": "General Medicine",
        "follow_up_interval_days": 7,
        "selection_weight": 6,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'Observation', 'DiagnosticReport', 'DocumentReference'],
    },

    {
        "case_id": "CASE004",
        "name": "Dengue Fever",
        "department_reference": "DEP001",
        "specialty_reference": "SP001",
        "diagnosis_reference": "DXGM004",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "High grade fever with retro-orbital pain",
        },
        "clinical_history": "Suspected dengue, advised testing and monitoring",
        "medication_references": ['MED000001', 'MED000006'],
        "observation_references": ['OBS000004', 'OBS000001'],
        "lab_references": ['LAB000007', 'LAB000001'],
        "procedure_references": ['PROC000002'],
        "vaccine_references": [],
        "document_types": ['Prescription', 'Diagnostic Report'],
        "billing_profile": "General Medicine",
        "follow_up_interval_days": 5,
        "selection_weight": 3,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'Observation', 'DiagnosticReport', 'Procedure', 'DocumentReference'],
    },

    {
        "case_id": "CASE005",
        "name": "Typhoid Fever",
        "department_reference": "DEP001",
        "specialty_reference": "SP001",
        "diagnosis_reference": "DXGM005",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Prolonged fever with abdominal discomfort",
        },
        "clinical_history": "Suspected enteric fever, started on antibiotics",
        "medication_references": ['MED000009', 'MED000001'],
        "observation_references": ['OBS000004'],
        "lab_references": ['LAB000001'],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription', 'Diagnostic Report'],
        "billing_profile": "General Medicine",
        "follow_up_interval_days": 10,
        "selection_weight": 2,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'Observation', 'DiagnosticReport', 'DocumentReference'],
    },

    {
        "case_id": "CASE006",
        "name": "Acute Gastroenteritis",
        "department_reference": "DEP001",
        "specialty_reference": "SP001",
        "diagnosis_reference": "DXGM006",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Loose stools and vomiting since yesterday",
        },
        "clinical_history": "Acute gastroenteritis, hydration and rest advised",
        "medication_references": ['MED000006', 'MED000008'],
        "observation_references": ['OBS000004'],
        "lab_references": ['LAB000008'],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription'],
        "billing_profile": "General Medicine",
        "follow_up_interval_days": 5,
        "selection_weight": 5,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'Observation', 'DiagnosticReport', 'DocumentReference'],
    },

    {
        "case_id": "CASE007",
        "name": "Iron Deficiency Anemia",
        "department_reference": "DEP001",
        "specialty_reference": "SP001",
        "diagnosis_reference": "DXGM007",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Fatigue and pallor",
        },
        "clinical_history": "Iron deficiency anemia on supplementation, follow-up review",
        "medication_references": ['MED000007'],
        "observation_references": ['OBS000005'],
        "lab_references": ['LAB000001'],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription', 'Diagnostic Report'],
        "billing_profile": "General Medicine",
        "follow_up_interval_days": 60,
        "selection_weight": 4,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'Observation', 'DiagnosticReport', 'DocumentReference'],
    },

    {
        "case_id": "CASE008",
        "name": "Hypothyroidism",
        "department_reference": "DEP001",
        "specialty_reference": "SP001",
        "diagnosis_reference": "DXGM008",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Fatigue and weight gain",
        },
        "clinical_history": "Known hypothyroid on replacement therapy, routine review",
        "medication_references": ['MED000012'],
        "observation_references": ['OBS000005', 'OBS000006'],
        "lab_references": ['LAB000004'],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription', 'Diagnostic Report'],
        "billing_profile": "General Medicine",
        "follow_up_interval_days": 90,
        "selection_weight": 4,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'Observation', 'DiagnosticReport', 'DocumentReference'],
    },

    {
        "case_id": "CASE009",
        "name": "Vitamin D Deficiency",
        "department_reference": "DEP001",
        "specialty_reference": "SP001",
        "diagnosis_reference": "DXGM009",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Generalised body ache and weakness",
        },
        "clinical_history": "Advised Vitamin D supplementation after review",
        "medication_references": ['MED000013'],
        "observation_references": [],
        "lab_references": [],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription'],
        "billing_profile": "General Medicine",
        "follow_up_interval_days": 90,
        "selection_weight": 3,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'DocumentReference'],
    },

    {
        "case_id": "CASE010",
        "name": "Hyperlipidemia",
        "department_reference": "DEP001",
        "specialty_reference": "SP001",
        "diagnosis_reference": "DXGM010",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Routine health check-up",
        },
        "clinical_history": "Dyslipidemia identified on screening, lifestyle advice given",
        "medication_references": ['MED000011'],
        "observation_references": ['OBS000001'],
        "lab_references": ['LAB000005'],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription', 'Diagnostic Report'],
        "billing_profile": "General Medicine",
        "follow_up_interval_days": 90,
        "selection_weight": 4,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'Observation', 'DiagnosticReport', 'DocumentReference'],
    },

    {
        "case_id": "CASE011",
        "name": "Stable Angina",
        "department_reference": "DEP002",
        "specialty_reference": "SP002",
        "diagnosis_reference": "DXCD001",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Exertional chest discomfort",
        },
        "clinical_history": "Known stable angina, on anti-anginal therapy",
        "medication_references": ['MED000002'],
        "observation_references": ['OBS000001', 'OBS000002'],
        "lab_references": ['LAB000005'],
        "procedure_references": ['PROC000003'],
        "vaccine_references": [],
        "document_types": ['Prescription', 'Diagnostic Report'],
        "billing_profile": "Cardiology",
        "follow_up_interval_days": 30,
        "selection_weight": 5,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'Observation', 'DiagnosticReport', 'Procedure', 'DocumentReference'],
    },

    {
        "case_id": "CASE012",
        "name": "Congestive Heart Failure",
        "department_reference": "DEP002",
        "specialty_reference": "SP002",
        "diagnosis_reference": "DXCD002",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Breathlessness on exertion and leg swelling",
        },
        "clinical_history": "Known heart failure, follow-up for symptom control",
        "medication_references": ['MED000002'],
        "observation_references": ['OBS000001', 'OBS000002', 'OBS000008'],
        "lab_references": ['LAB000005'],
        "procedure_references": ['PROC000003'],
        "vaccine_references": [],
        "document_types": ['Prescription', 'Diagnostic Report'],
        "billing_profile": "Cardiology",
        "follow_up_interval_days": 30,
        "selection_weight": 3,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'Observation', 'DiagnosticReport', 'Procedure', 'DocumentReference'],
    },

    {
        "case_id": "CASE013",
        "name": "Atrial Fibrillation",
        "department_reference": "DEP002",
        "specialty_reference": "SP002",
        "diagnosis_reference": "DXCD003",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Palpitations and irregular heartbeat",
        },
        "clinical_history": "Known atrial fibrillation on rate control, routine review",
        "medication_references": ['MED000014'],
        "observation_references": ['OBS000001', 'OBS000002'],
        "lab_references": [],
        "procedure_references": ['PROC000003'],
        "vaccine_references": [],
        "document_types": ['Prescription', 'Diagnostic Report'],
        "billing_profile": "Cardiology",
        "follow_up_interval_days": 30,
        "selection_weight": 3,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'Observation', 'Procedure', 'DocumentReference'],
    },

    {
        "case_id": "CASE014",
        "name": "Ischemic Heart Disease",
        "department_reference": "DEP002",
        "specialty_reference": "SP002",
        "diagnosis_reference": "DXCD004",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Chest heaviness on exertion",
        },
        "clinical_history": "Known ischemic heart disease, on secondary prevention medication",
        "medication_references": ['MED000002', 'MED000003'],
        "observation_references": ['OBS000001', 'OBS000002'],
        "lab_references": ['LAB000005'],
        "procedure_references": ['PROC000003'],
        "vaccine_references": [],
        "document_types": ['Prescription', 'Diagnostic Report'],
        "billing_profile": "Cardiology",
        "follow_up_interval_days": 60,
        "selection_weight": 4,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'Observation', 'DiagnosticReport', 'Procedure', 'DocumentReference'],
    },

    {
        "case_id": "CASE015",
        "name": "Hypertensive Heart Disease",
        "department_reference": "DEP002",
        "specialty_reference": "SP002",
        "diagnosis_reference": "DXCD005",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Breathlessness with long standing hypertension",
        },
        "clinical_history": "Hypertensive heart disease, on combination antihypertensive therapy",
        "medication_references": ['MED000002', 'MED000003'],
        "observation_references": ['OBS000001', 'OBS000002'],
        "lab_references": ['LAB000005'],
        "procedure_references": ['PROC000003'],
        "vaccine_references": [],
        "document_types": ['Prescription', 'Diagnostic Report'],
        "billing_profile": "Cardiology",
        "follow_up_interval_days": 30,
        "selection_weight": 4,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'Observation', 'DiagnosticReport', 'Procedure', 'DocumentReference'],
    },

    {
        "case_id": "CASE016",
        "name": "Bronchial Asthma",
        "department_reference": "DEP003",
        "specialty_reference": "SP003",
        "diagnosis_reference": "DXPL001",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Recurrent wheeze and breathlessness",
        },
        "clinical_history": "Known asthmatic, follow-up for inhaler technique and control",
        "medication_references": ['MED000005'],
        "observation_references": ['OBS000003', 'OBS000008'],
        "lab_references": [],
        "procedure_references": ['PROC000001'],
        "vaccine_references": [],
        "document_types": ['Prescription'],
        "billing_profile": "Pulmonology",
        "follow_up_interval_days": 30,
        "selection_weight": 6,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'Observation', 'Procedure', 'DocumentReference'],
    },

    {
        "case_id": "CASE017",
        "name": "COPD",
        "department_reference": "DEP003",
        "specialty_reference": "SP003",
        "diagnosis_reference": "DXPL002",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Chronic cough with breathlessness",
        },
        "clinical_history": "Known COPD patient on bronchodilator therapy",
        "medication_references": ['MED000005'],
        "observation_references": ['OBS000003', 'OBS000008'],
        "lab_references": [],
        "procedure_references": ['PROC000001'],
        "vaccine_references": [],
        "document_types": ['Prescription'],
        "billing_profile": "Pulmonology",
        "follow_up_interval_days": 30,
        "selection_weight": 4,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'Observation', 'Procedure', 'DocumentReference'],
    },

    {
        "case_id": "CASE018",
        "name": "Community Acquired Pneumonia",
        "department_reference": "DEP003",
        "specialty_reference": "SP003",
        "diagnosis_reference": "DXPL003",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Fever with cough and breathlessness",
        },
        "clinical_history": "Acute community acquired pneumonia, started on antibiotics",
        "medication_references": ['MED000009', 'MED000001'],
        "observation_references": ['OBS000004', 'OBS000008', 'OBS000003'],
        "lab_references": ['LAB000001'],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription', 'Diagnostic Report'],
        "billing_profile": "Pulmonology",
        "follow_up_interval_days": 7,
        "selection_weight": 3,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'Observation', 'DiagnosticReport', 'DocumentReference'],
    },

    {
        "case_id": "CASE019",
        "name": "Acute Bronchitis",
        "department_reference": "DEP003",
        "specialty_reference": "SP003",
        "diagnosis_reference": "DXPL004",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Cough with mucus production for a week",
        },
        "clinical_history": "Acute bronchitis, symptomatic management advised",
        "medication_references": ['MED000001', 'MED000005'],
        "observation_references": ['OBS000003'],
        "lab_references": [],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription'],
        "billing_profile": "Pulmonology",
        "follow_up_interval_days": 7,
        "selection_weight": 5,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'Observation', 'DocumentReference'],
    },

    {
        "case_id": "CASE020",
        "name": "Pulmonary Tuberculosis",
        "department_reference": "DEP003",
        "specialty_reference": "SP003",
        "diagnosis_reference": "DXPL005",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Chronic cough with evening rise of fever and weight loss",
        },
        "clinical_history": "Suspected pulmonary tuberculosis, referred for sputum testing and DOTS",
        "medication_references": ['MED000020'],
        "observation_references": ['OBS000004', 'OBS000005'],
        "lab_references": ['LAB000001'],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription', 'Diagnostic Report', 'Referral Note'],
        "billing_profile": "Pulmonology",
        "follow_up_interval_days": 14,
        "selection_weight": 2,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'Observation', 'DiagnosticReport', 'DocumentReference'],
    },

    {
        "case_id": "CASE021",
        "name": "Hyperthyroidism",
        "department_reference": "DEP004",
        "specialty_reference": "SP004",
        "diagnosis_reference": "DXEN001",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Palpitations, weight loss and heat intolerance",
        },
        "clinical_history": "Newly diagnosed hyperthyroidism, started on antithyroid treatment",
        "medication_references": ['MED000015'],
        "observation_references": ['OBS000001', 'OBS000002', 'OBS000005'],
        "lab_references": ['LAB000004'],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription', 'Diagnostic Report'],
        "billing_profile": "Endocrinology",
        "follow_up_interval_days": 30,
        "selection_weight": 2,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'Observation', 'DiagnosticReport', 'DocumentReference'],
    },

    {
        "case_id": "CASE022",
        "name": "Obesity",
        "department_reference": "DEP004",
        "specialty_reference": "SP004",
        "diagnosis_reference": "DXEN002",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Progressive weight gain",
        },
        "clinical_history": "Counselled on diet and lifestyle modification",
        "medication_references": [],
        "observation_references": ['OBS000005', 'OBS000006'],
        "lab_references": ['LAB000005', 'LAB000006'],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription'],
        "billing_profile": "Endocrinology",
        "follow_up_interval_days": 60,
        "selection_weight": 3,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'Observation', 'DiagnosticReport', 'DocumentReference'],
    },

    {
        "case_id": "CASE023",
        "name": "Prediabetes",
        "department_reference": "DEP004",
        "specialty_reference": "SP004",
        "diagnosis_reference": "DXEN003",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Routine health screening",
        },
        "clinical_history": "Prediabetes detected on screening, lifestyle advice given",
        "medication_references": [],
        "observation_references": ['OBS000007'],
        "lab_references": ['LAB000006'],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Diagnostic Report'],
        "billing_profile": "Endocrinology",
        "follow_up_interval_days": 90,
        "selection_weight": 3,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'Observation', 'DiagnosticReport', 'DocumentReference'],
    },

    {
        "case_id": "CASE024",
        "name": "Vitamin B12 Deficiency",
        "department_reference": "DEP004",
        "specialty_reference": "SP004",
        "diagnosis_reference": "DXEN004",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Tingling in hands and feet with fatigue",
        },
        "clinical_history": "Vitamin B12 deficiency identified, supplementation started",
        "medication_references": ['MED000016'],
        "observation_references": ['OBS000005'],
        "lab_references": ['LAB000001'],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription', 'Diagnostic Report'],
        "billing_profile": "Endocrinology",
        "follow_up_interval_days": 60,
        "selection_weight": 2,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'Observation', 'DiagnosticReport', 'DocumentReference'],
    },

    {
        "case_id": "CASE025",
        "name": "Metabolic Syndrome",
        "department_reference": "DEP004",
        "specialty_reference": "SP004",
        "diagnosis_reference": "DXEN005",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Routine health check-up",
        },
        "clinical_history": "Metabolic syndrome identified on screening, lifestyle modification advised",
        "medication_references": ['MED000004'],
        "observation_references": ['OBS000001', 'OBS000007'],
        "lab_references": ['LAB000005', 'LAB000006'],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription', 'Diagnostic Report'],
        "billing_profile": "Endocrinology",
        "follow_up_interval_days": 90,
        "selection_weight": 2,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'Observation', 'DiagnosticReport', 'DocumentReference'],
    },

    {
        "case_id": "CASE026",
        "name": "Knee Osteoarthritis",
        "department_reference": "DEP005",
        "specialty_reference": "SP005",
        "diagnosis_reference": "DXOR001",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Knee pain on walking and climbing stairs",
        },
        "clinical_history": "Chronic knee osteoarthritis, on symptomatic treatment",
        "medication_references": ['MED000017'],
        "observation_references": [],
        "lab_references": [],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription'],
        "billing_profile": "Orthopedics",
        "follow_up_interval_days": 60,
        "selection_weight": 5,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'DocumentReference'],
    },

    {
        "case_id": "CASE027",
        "name": "Low Back Pain",
        "department_reference": "DEP005",
        "specialty_reference": "SP005",
        "diagnosis_reference": "DXOR002",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Lower back pain for a week",
        },
        "clinical_history": "Mechanical low back pain, advised physiotherapy",
        "medication_references": ['MED000017'],
        "observation_references": [],
        "lab_references": [],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription'],
        "billing_profile": "Orthopedics",
        "follow_up_interval_days": 14,
        "selection_weight": 6,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'DocumentReference'],
    },

    {
        "case_id": "CASE028",
        "name": "Cervical Spondylosis",
        "department_reference": "DEP005",
        "specialty_reference": "SP005",
        "diagnosis_reference": "DXOR003",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Neck pain with stiffness",
        },
        "clinical_history": "Chronic cervical spondylosis, symptomatic management",
        "medication_references": ['MED000017'],
        "observation_references": [],
        "lab_references": [],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription'],
        "billing_profile": "Orthopedics",
        "follow_up_interval_days": 30,
        "selection_weight": 4,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'DocumentReference'],
    },

    {
        "case_id": "CASE029",
        "name": "Ankle Sprain",
        "department_reference": "DEP005",
        "specialty_reference": "SP005",
        "diagnosis_reference": "DXOR004",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Ankle pain and swelling after a fall",
        },
        "clinical_history": "Acute ankle sprain, rest and immobilization advised",
        "medication_references": [],
        "observation_references": [],
        "lab_references": [],
        "procedure_references": ['PROC000005'],
        "vaccine_references": [],
        "document_types": ['Prescription'],
        "billing_profile": "Orthopedics",
        "follow_up_interval_days": 14,
        "selection_weight": 4,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'Procedure', 'DocumentReference'],
    },

    {
        "case_id": "CASE030",
        "name": "Distal Radius Fracture",
        "department_reference": "DEP005",
        "specialty_reference": "SP005",
        "diagnosis_reference": "DXOR005",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Wrist pain and deformity after a fall",
        },
        "clinical_history": "Acute distal radius fracture, casted and advised follow-up",
        "medication_references": ['MED000001'],
        "observation_references": [],
        "lab_references": [],
        "procedure_references": ['PROC000005'],
        "vaccine_references": [],
        "document_types": ['Prescription', 'Discharge Summary'],
        "billing_profile": "Orthopedics",
        "follow_up_interval_days": 21,
        "selection_weight": 2,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'Procedure', 'DocumentReference'],
    },

    {
        "case_id": "CASE031",
        "name": "Normal Pregnancy",
        "department_reference": "DEP006",
        "specialty_reference": "SP006",
        "diagnosis_reference": "DXGY001",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Routine antenatal check-up",
        },
        "clinical_history": "Antenatal visit, pregnancy progressing well",
        "medication_references": ['MED000007'],
        "observation_references": ['OBS000001', 'OBS000005'],
        "lab_references": ['LAB000001', 'LAB000008'],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription', 'Diagnostic Report'],
        "billing_profile": "Gynecology",
        "follow_up_interval_days": 30,
        "selection_weight": 6,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'Observation', 'DiagnosticReport', 'DocumentReference'],
    },

    {
        "case_id": "CASE032",
        "name": "PCOS",
        "department_reference": "DEP006",
        "specialty_reference": "SP006",
        "diagnosis_reference": "DXGY002",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Irregular menstrual cycles",
        },
        "clinical_history": "PCOS on follow-up, lifestyle and medication review",
        "medication_references": [],
        "observation_references": ['OBS000005', 'OBS000006'],
        "lab_references": ['LAB000006'],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription', 'Diagnostic Report'],
        "billing_profile": "Gynecology",
        "follow_up_interval_days": 90,
        "selection_weight": 4,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'Observation', 'DiagnosticReport', 'DocumentReference'],
    },

    {
        "case_id": "CASE033",
        "name": "Dysmenorrhea",
        "department_reference": "DEP006",
        "specialty_reference": "SP006",
        "diagnosis_reference": "DXGY003",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Painful periods",
        },
        "clinical_history": "Primary dysmenorrhea, symptomatic treatment given",
        "medication_references": ['MED000001'],
        "observation_references": [],
        "lab_references": [],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription'],
        "billing_profile": "Gynecology",
        "follow_up_interval_days": 30,
        "selection_weight": 4,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'DocumentReference'],
    },

    {
        "case_id": "CASE034",
        "name": "Menopause",
        "department_reference": "DEP006",
        "specialty_reference": "SP006",
        "diagnosis_reference": "DXGY004",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Hot flashes and irregular periods",
        },
        "clinical_history": "Perimenopausal symptoms, counselled and reviewed",
        "medication_references": [],
        "observation_references": ['OBS000001'],
        "lab_references": [],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription'],
        "billing_profile": "Gynecology",
        "follow_up_interval_days": 90,
        "selection_weight": 2,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'Observation', 'DocumentReference'],
    },

    {
        "case_id": "CASE035",
        "name": "Urinary Tract Infection",
        "department_reference": "DEP006",
        "specialty_reference": "SP006",
        "diagnosis_reference": "DXGY005",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Burning micturition",
        },
        "clinical_history": "Urinary tract infection, started on antibiotics",
        "medication_references": ['MED000009'],
        "observation_references": ['OBS000004'],
        "lab_references": ['LAB000008'],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription', 'Diagnostic Report'],
        "billing_profile": "Gynecology",
        "follow_up_interval_days": 7,
        "selection_weight": 4,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'Observation', 'DiagnosticReport', 'DocumentReference'],
    },

    {
        "case_id": "CASE036",
        "name": "Acute URI",
        "department_reference": "DEP007",
        "specialty_reference": "SP007",
        "diagnosis_reference": "DXPD001",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Cough and runny nose",
        },
        "clinical_history": "Acute upper respiratory infection, symptomatic treatment",
        "medication_references": ['MED000001', 'MED000010'],
        "observation_references": ['OBS000004'],
        "lab_references": [],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription'],
        "billing_profile": "Pediatrics",
        "follow_up_interval_days": 7,
        "selection_weight": 7,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'Observation', 'DocumentReference'],
    },

    {
        "case_id": "CASE037",
        "name": "Acute Diarrhea",
        "department_reference": "DEP007",
        "specialty_reference": "SP007",
        "diagnosis_reference": "DXPD002",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Loose stools for 2 days",
        },
        "clinical_history": "Acute diarrhea, ORS and hydration advised",
        "medication_references": ['MED000006'],
        "observation_references": ['OBS000004'],
        "lab_references": [],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription'],
        "billing_profile": "Pediatrics",
        "follow_up_interval_days": 5,
        "selection_weight": 5,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'Observation', 'DocumentReference'],
    },

    {
        "case_id": "CASE038",
        "name": "Childhood Fever",
        "department_reference": "DEP007",
        "specialty_reference": "SP007",
        "diagnosis_reference": "DXPD003",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Fever for 2 days",
        },
        "clinical_history": "Acute febrile illness in child, symptomatic management",
        "medication_references": ['MED000001'],
        "observation_references": ['OBS000004'],
        "lab_references": [],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription'],
        "billing_profile": "Pediatrics",
        "follow_up_interval_days": 5,
        "selection_weight": 6,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'Observation', 'DocumentReference'],
    },

    {
        "case_id": "CASE039",
        "name": "Otitis Media",
        "department_reference": "DEP007",
        "specialty_reference": "SP007",
        "diagnosis_reference": "DXPD004",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Ear pain and irritability",
        },
        "clinical_history": "Acute otitis media, started on antibiotics",
        "medication_references": ['MED000009', 'MED000001'],
        "observation_references": ['OBS000004'],
        "lab_references": [],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription'],
        "billing_profile": "Pediatrics",
        "follow_up_interval_days": 7,
        "selection_weight": 3,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'Observation', 'DocumentReference'],
    },

    {
        "case_id": "CASE040",
        "name": "Routine Immunization Visit",
        "department_reference": "DEP007",
        "specialty_reference": "SP007",
        "diagnosis_reference": "DXPD005",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Due for scheduled vaccination",
        },
        "clinical_history": "Routine immunization visit as per schedule",
        "medication_references": [],
        "observation_references": ['OBS000005', 'OBS000006'],
        "lab_references": [],
        "procedure_references": [],
        "vaccine_references": ['VAC000002', 'VAC000003'],
        "document_types": ['Wellness Record', 'Immunization'],
        "billing_profile": "Pediatrics",
        "follow_up_interval_days": 180,
        "selection_weight": 5,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'Observation', 'Immunization', 'DocumentReference'],
    },

    {
        "case_id": "CASE041",
        "name": "Acne Vulgaris",
        "department_reference": "DEP008",
        "specialty_reference": "SP008",
        "diagnosis_reference": "DXDM001",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Facial acne for several months",
        },
        "clinical_history": "Acne vulgaris, started on topical treatment",
        "medication_references": ['MED000026'],
        "observation_references": [],
        "lab_references": [],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription'],
        "billing_profile": "Dermatology",
        "follow_up_interval_days": 30,
        "selection_weight": 4,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'DocumentReference'],
    },

    {
        "case_id": "CASE042",
        "name": "Tinea Corporis",
        "department_reference": "DEP008",
        "specialty_reference": "SP008",
        "diagnosis_reference": "DXDM002",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Itchy circular skin rash",
        },
        "clinical_history": "Fungal skin infection, started on antifungal treatment",
        "medication_references": ['MED000025'],
        "observation_references": [],
        "lab_references": [],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription'],
        "billing_profile": "Dermatology",
        "follow_up_interval_days": 14,
        "selection_weight": 4,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'DocumentReference'],
    },

    {
        "case_id": "CASE043",
        "name": "Atopic Dermatitis",
        "department_reference": "DEP008",
        "specialty_reference": "SP008",
        "diagnosis_reference": "DXDM003",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Itchy dry skin patches",
        },
        "clinical_history": "Chronic atopic dermatitis, on symptomatic management",
        "medication_references": ['MED000010', 'MED000021'],
        "observation_references": [],
        "lab_references": [],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription'],
        "billing_profile": "Dermatology",
        "follow_up_interval_days": 30,
        "selection_weight": 3,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'DocumentReference'],
    },

    {
        "case_id": "CASE044",
        "name": "Psoriasis",
        "department_reference": "DEP008",
        "specialty_reference": "SP008",
        "diagnosis_reference": "DXDM004",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Scaly skin plaques",
        },
        "clinical_history": "Chronic psoriasis on follow-up",
        "medication_references": ['MED000021'],
        "observation_references": [],
        "lab_references": [],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription'],
        "billing_profile": "Dermatology",
        "follow_up_interval_days": 60,
        "selection_weight": 2,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'DocumentReference'],
    },

    {
        "case_id": "CASE045",
        "name": "Urticaria",
        "department_reference": "DEP008",
        "specialty_reference": "SP008",
        "diagnosis_reference": "DXDM005",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Itchy skin rash with wheals",
        },
        "clinical_history": "Acute urticaria, started on antihistamines",
        "medication_references": ['MED000010'],
        "observation_references": [],
        "lab_references": [],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription'],
        "billing_profile": "Dermatology",
        "follow_up_interval_days": 7,
        "selection_weight": 3,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'DocumentReference'],
    },

    {
        "case_id": "CASE046",
        "name": "Acute Sinusitis",
        "department_reference": "DEP009",
        "specialty_reference": "SP009",
        "diagnosis_reference": "DXET001",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Facial pain and nasal congestion",
        },
        "clinical_history": "Acute sinusitis, symptomatic treatment started",
        "medication_references": ['MED000001', 'MED000010'],
        "observation_references": ['OBS000004'],
        "lab_references": [],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription'],
        "billing_profile": "ENT",
        "follow_up_interval_days": 10,
        "selection_weight": 4,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'Observation', 'DocumentReference'],
    },

    {
        "case_id": "CASE047",
        "name": "Acute Pharyngitis",
        "department_reference": "DEP009",
        "specialty_reference": "SP009",
        "diagnosis_reference": "DXET002",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Sore throat and pain on swallowing",
        },
        "clinical_history": "Acute pharyngitis, symptomatic treatment given",
        "medication_references": ['MED000001'],
        "observation_references": ['OBS000004'],
        "lab_references": [],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription'],
        "billing_profile": "ENT",
        "follow_up_interval_days": 7,
        "selection_weight": 5,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'Observation', 'DocumentReference'],
    },

    {
        "case_id": "CASE048",
        "name": "Acute Tonsillitis",
        "department_reference": "DEP009",
        "specialty_reference": "SP009",
        "diagnosis_reference": "DXET003",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Sore throat with fever",
        },
        "clinical_history": "Acute tonsillitis, started on antibiotics",
        "medication_references": ['MED000009', 'MED000001'],
        "observation_references": ['OBS000004'],
        "lab_references": [],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription'],
        "billing_profile": "ENT",
        "follow_up_interval_days": 7,
        "selection_weight": 3,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'Observation', 'DocumentReference'],
    },

    {
        "case_id": "CASE049",
        "name": "Allergic Rhinitis",
        "department_reference": "DEP009",
        "specialty_reference": "SP009",
        "diagnosis_reference": "DXET004",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Sneezing and nasal itching",
        },
        "clinical_history": "Allergic rhinitis, on antihistamine therapy",
        "medication_references": ['MED000010'],
        "observation_references": [],
        "lab_references": [],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription'],
        "billing_profile": "ENT",
        "follow_up_interval_days": 30,
        "selection_weight": 4,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'DocumentReference'],
    },

    {
        "case_id": "CASE050",
        "name": "Otitis Externa",
        "department_reference": "DEP009",
        "specialty_reference": "SP009",
        "diagnosis_reference": "DXET005",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Ear pain and discharge",
        },
        "clinical_history": "Otitis externa, started on topical treatment",
        "medication_references": ['MED000023'],
        "observation_references": [],
        "lab_references": [],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription'],
        "billing_profile": "ENT",
        "follow_up_interval_days": 10,
        "selection_weight": 2,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'DocumentReference'],
    },

    {
        "case_id": "CASE051",
        "name": "Conjunctivitis",
        "department_reference": "DEP010",
        "specialty_reference": "SP010",
        "diagnosis_reference": "DXOP001",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Redness and watering of eyes",
        },
        "clinical_history": "Acute conjunctivitis, started on topical treatment",
        "medication_references": ['MED000022'],
        "observation_references": [],
        "lab_references": [],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription'],
        "billing_profile": "Ophthalmology",
        "follow_up_interval_days": 7,
        "selection_weight": 4,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'DocumentReference'],
    },

    {
        "case_id": "CASE052",
        "name": "Age-related Cataract",
        "department_reference": "DEP010",
        "specialty_reference": "SP010",
        "diagnosis_reference": "DXOP002",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Gradual blurring of vision",
        },
        "clinical_history": "Age related cataract, advised surgical evaluation",
        "medication_references": [],
        "observation_references": [],
        "lab_references": [],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Referral Note'],
        "billing_profile": "Ophthalmology",
        "follow_up_interval_days": 90,
        "selection_weight": 3,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'DocumentReference'],
    },

    {
        "case_id": "CASE053",
        "name": "Dry Eye Syndrome",
        "department_reference": "DEP010",
        "specialty_reference": "SP010",
        "diagnosis_reference": "DXOP003",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Eye irritation and dryness",
        },
        "clinical_history": "Chronic dry eye, on lubricant eye drops",
        "medication_references": ['MED000022'],
        "observation_references": [],
        "lab_references": [],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription'],
        "billing_profile": "Ophthalmology",
        "follow_up_interval_days": 60,
        "selection_weight": 3,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'DocumentReference'],
    },

    {
        "case_id": "CASE054",
        "name": "Refractive Error",
        "department_reference": "DEP010",
        "specialty_reference": "SP010",
        "diagnosis_reference": "DXOP004",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Difficulty in reading and distant vision",
        },
        "clinical_history": "Refractive error, advised corrective glasses",
        "medication_references": [],
        "observation_references": [],
        "lab_references": [],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription'],
        "billing_profile": "Ophthalmology",
        "follow_up_interval_days": 180,
        "selection_weight": 3,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'DocumentReference'],
    },

    {
        "case_id": "CASE055",
        "name": "Stye",
        "department_reference": "DEP010",
        "specialty_reference": "SP010",
        "diagnosis_reference": "DXOP005",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Painful swelling of eyelid",
        },
        "clinical_history": "Acute stye, started on topical treatment",
        "medication_references": ['MED000022'],
        "observation_references": [],
        "lab_references": [],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription'],
        "billing_profile": "Ophthalmology",
        "follow_up_interval_days": 7,
        "selection_weight": 2,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'DocumentReference'],
    },

    {
        "case_id": "CASE056",
        "name": "Migraine",
        "department_reference": "DEP011",
        "specialty_reference": "SP011",
        "diagnosis_reference": "DXNE001",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Recurrent one-sided headache with nausea",
        },
        "clinical_history": "Known migraine, on prophylactic and abortive therapy",
        "medication_references": ['MED000001'],
        "observation_references": ['OBS000001'],
        "lab_references": [],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription'],
        "billing_profile": "Neurology",
        "follow_up_interval_days": 30,
        "selection_weight": 5,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'Observation', 'DocumentReference'],
    },

    {
        "case_id": "CASE057",
        "name": "Tension Headache",
        "department_reference": "DEP011",
        "specialty_reference": "SP011",
        "diagnosis_reference": "DXNE002",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Band-like headache",
        },
        "clinical_history": "Tension type headache, symptomatic treatment",
        "medication_references": ['MED000001'],
        "observation_references": ['OBS000001'],
        "lab_references": [],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription'],
        "billing_profile": "Neurology",
        "follow_up_interval_days": 14,
        "selection_weight": 5,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'Observation', 'DocumentReference'],
    },

    {
        "case_id": "CASE058",
        "name": "Epilepsy",
        "department_reference": "DEP011",
        "specialty_reference": "SP011",
        "diagnosis_reference": "DXNE003",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Recurrent episodes of seizures",
        },
        "clinical_history": "Known epileptic on antiepileptic therapy, routine review",
        "medication_references": ['MED000018'],
        "observation_references": [],
        "lab_references": [],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription'],
        "billing_profile": "Neurology",
        "follow_up_interval_days": 60,
        "selection_weight": 3,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'DocumentReference'],
    },

    {
        "case_id": "CASE059",
        "name": "Peripheral Neuropathy",
        "department_reference": "DEP011",
        "specialty_reference": "SP011",
        "diagnosis_reference": "DXNE004",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Tingling and numbness in feet",
        },
        "clinical_history": "Diabetic peripheral neuropathy, on symptomatic treatment",
        "medication_references": ['MED000004'],
        "observation_references": ['OBS000007'],
        "lab_references": ['LAB000006'],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription', 'Diagnostic Report'],
        "billing_profile": "Neurology",
        "follow_up_interval_days": 60,
        "selection_weight": 3,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'Observation', 'DiagnosticReport', 'DocumentReference'],
    },

    {
        "case_id": "CASE060",
        "name": "Vertigo",
        "department_reference": "DEP011",
        "specialty_reference": "SP011",
        "diagnosis_reference": "DXNE005",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Spinning sensation and imbalance",
        },
        "clinical_history": "Acute vertigo, symptomatic treatment given",
        "medication_references": [],
        "observation_references": ['OBS000001'],
        "lab_references": [],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription'],
        "billing_profile": "Neurology",
        "follow_up_interval_days": 14,
        "selection_weight": 3,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'Observation', 'DocumentReference'],
    },

    {
        "case_id": "CASE061",
        "name": "Urinary Tract Infection",
        "department_reference": "DEP012",
        "specialty_reference": "SP012",
        "diagnosis_reference": "DXUR001",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Burning micturition and urgency",
        },
        "clinical_history": "Urinary tract infection, started on antibiotics",
        "medication_references": ['MED000009'],
        "observation_references": ['OBS000004'],
        "lab_references": ['LAB000008'],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription', 'Diagnostic Report'],
        "billing_profile": "Urology",
        "follow_up_interval_days": 7,
        "selection_weight": 5,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'Observation', 'DiagnosticReport', 'DocumentReference'],
    },

    {
        "case_id": "CASE062",
        "name": "Benign Prostatic Hyperplasia",
        "department_reference": "DEP012",
        "specialty_reference": "SP012",
        "diagnosis_reference": "DXUR002",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Difficulty in urination and weak stream",
        },
        "clinical_history": "Benign prostatic hyperplasia, on medical management",
        "medication_references": ['MED000024'],
        "observation_references": [],
        "lab_references": [],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription'],
        "billing_profile": "Urology",
        "follow_up_interval_days": 60,
        "selection_weight": 3,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'DocumentReference'],
    },

    {
        "case_id": "CASE063",
        "name": "Renal Calculus",
        "department_reference": "DEP012",
        "specialty_reference": "SP012",
        "diagnosis_reference": "DXUR003",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Severe flank pain radiating to groin",
        },
        "clinical_history": "Renal colic, advised imaging and pain management",
        "medication_references": ['MED000001'],
        "observation_references": [],
        "lab_references": ['LAB000003'],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription', 'Diagnostic Report'],
        "billing_profile": "Urology",
        "follow_up_interval_days": 14,
        "selection_weight": 3,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'DiagnosticReport', 'DocumentReference'],
    },

    {
        "case_id": "CASE064",
        "name": "Hematuria",
        "department_reference": "DEP012",
        "specialty_reference": "SP012",
        "diagnosis_reference": "DXUR004",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Blood in urine",
        },
        "clinical_history": "Hematuria under evaluation",
        "medication_references": [],
        "observation_references": [],
        "lab_references": ['LAB000008', 'LAB000003'],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Diagnostic Report'],
        "billing_profile": "Urology",
        "follow_up_interval_days": 14,
        "selection_weight": 2,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'DiagnosticReport', 'DocumentReference'],
    },

    {
        "case_id": "CASE065",
        "name": "Hydrocele",
        "department_reference": "DEP012",
        "specialty_reference": "SP012",
        "diagnosis_reference": "DXUR005",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Painless scrotal swelling",
        },
        "clinical_history": "Hydrocele, advised surgical evaluation",
        "medication_references": [],
        "observation_references": [],
        "lab_references": [],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Referral Note'],
        "billing_profile": "Urology",
        "follow_up_interval_days": 90,
        "selection_weight": 2,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'DocumentReference'],
    },

    {
        "case_id": "CASE066",
        "name": "Generalized Anxiety Disorder",
        "department_reference": "DEP013",
        "specialty_reference": "SP013",
        "diagnosis_reference": "DXPS001",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Excessive worry and restlessness",
        },
        "clinical_history": "Generalized anxiety disorder, on follow-up management",
        "medication_references": ['MED000019'],
        "observation_references": [],
        "lab_references": [],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription'],
        "billing_profile": "Psychiatry",
        "follow_up_interval_days": 30,
        "selection_weight": 3,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'DocumentReference'],
    },

    {
        "case_id": "CASE067",
        "name": "Major Depressive Disorder",
        "department_reference": "DEP013",
        "specialty_reference": "SP013",
        "diagnosis_reference": "DXPS002",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Persistent low mood and loss of interest",
        },
        "clinical_history": "Major depressive disorder, on follow-up management",
        "medication_references": ['MED000019'],
        "observation_references": [],
        "lab_references": [],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription'],
        "billing_profile": "Psychiatry",
        "follow_up_interval_days": 30,
        "selection_weight": 3,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'DocumentReference'],
    },

    {
        "case_id": "CASE068",
        "name": "Insomnia",
        "department_reference": "DEP013",
        "specialty_reference": "SP013",
        "diagnosis_reference": "DXPS003",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Difficulty falling and staying asleep",
        },
        "clinical_history": "Chronic insomnia, sleep hygiene counselling given",
        "medication_references": [],
        "observation_references": [],
        "lab_references": [],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription'],
        "billing_profile": "Psychiatry",
        "follow_up_interval_days": 30,
        "selection_weight": 2,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'DocumentReference'],
    },

    {
        "case_id": "CASE069",
        "name": "Panic Disorder",
        "department_reference": "DEP013",
        "specialty_reference": "SP013",
        "diagnosis_reference": "DXPS004",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Recurrent episodes of intense fear with palpitations",
        },
        "clinical_history": "Panic disorder, on follow-up management",
        "medication_references": ['MED000019'],
        "observation_references": ['OBS000002'],
        "lab_references": [],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription'],
        "billing_profile": "Psychiatry",
        "follow_up_interval_days": 30,
        "selection_weight": 2,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'Observation', 'DocumentReference'],
    },

    {
        "case_id": "CASE070",
        "name": "Adjustment Disorder",
        "department_reference": "DEP013",
        "specialty_reference": "SP013",
        "diagnosis_reference": "DXPS005",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Difficulty coping with a recent life stressor",
        },
        "clinical_history": "Adjustment disorder, supportive counselling given",
        "medication_references": [],
        "observation_references": [],
        "lab_references": [],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription'],
        "billing_profile": "Psychiatry",
        "follow_up_interval_days": 30,
        "selection_weight": 2,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'DocumentReference'],
    },

    {
        "case_id": "CASE071",
        "name": "Acute Appendicitis",
        "department_reference": "DEP014",
        "specialty_reference": "SP014",
        "diagnosis_reference": "DXSG001",
        "encounter": {
            "type": "IPD",
            "visit_reason": "Admission",
            "chief_complaint": "Right lower abdominal pain with fever",
        },
        "clinical_history": "Acute appendicitis, admitted for surgical management",
        "medication_references": ['MED000001'],
        "observation_references": ['OBS000004'],
        "lab_references": ['LAB000001'],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription', 'Discharge Summary'],
        "billing_profile": "General Surgery",
        "follow_up_interval_days": 14,
        "selection_weight": 3,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'Observation', 'DiagnosticReport', 'DocumentReference'],
    },

    {
        "case_id": "CASE072",
        "name": "Inguinal Hernia",
        "department_reference": "DEP014",
        "specialty_reference": "SP014",
        "diagnosis_reference": "DXSG002",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Swelling in the groin on straining",
        },
        "clinical_history": "Inguinal hernia, advised elective surgical repair",
        "medication_references": [],
        "observation_references": [],
        "lab_references": [],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Referral Note'],
        "billing_profile": "General Surgery",
        "follow_up_interval_days": 30,
        "selection_weight": 3,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'DocumentReference'],
    },

    {
        "case_id": "CASE073",
        "name": "Cholelithiasis",
        "department_reference": "DEP014",
        "specialty_reference": "SP014",
        "diagnosis_reference": "DXSG003",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Right upper abdominal pain after meals",
        },
        "clinical_history": "Gallstone disease, advised surgical evaluation",
        "medication_references": ['MED000008'],
        "observation_references": [],
        "lab_references": ['LAB000004'],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription', 'Diagnostic Report'],
        "billing_profile": "General Surgery",
        "follow_up_interval_days": 30,
        "selection_weight": 3,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'DiagnosticReport', 'DocumentReference'],
    },

    {
        "case_id": "CASE074",
        "name": "Pilonidal Sinus",
        "department_reference": "DEP014",
        "specialty_reference": "SP014",
        "diagnosis_reference": "DXSG004",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Discharge and pain over the lower back",
        },
        "clinical_history": "Pilonidal sinus, advised minor surgical procedure",
        "medication_references": ['MED000009'],
        "observation_references": [],
        "lab_references": [],
        "procedure_references": ['PROC000005'],
        "vaccine_references": [],
        "document_types": ['Prescription'],
        "billing_profile": "General Surgery",
        "follow_up_interval_days": 14,
        "selection_weight": 2,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'Procedure', 'DocumentReference'],
    },

    {
        "case_id": "CASE075",
        "name": "Hemorrhoids",
        "department_reference": "DEP014",
        "specialty_reference": "SP014",
        "diagnosis_reference": "DXSG005",
        "encounter": {
            "type": "OPD",
            "visit_reason": "Follow-up",
            "chief_complaint": "Pain and bleeding during defecation",
        },
        "clinical_history": "Hemorrhoids, on conservative management",
        "medication_references": [],
        "observation_references": [],
        "lab_references": [],
        "procedure_references": [],
        "vaccine_references": [],
        "document_types": ['Prescription'],
        "billing_profile": "General Surgery",
        "follow_up_interval_days": 30,
        "selection_weight": 3,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'DocumentReference'],
    },

    {
        "case_id": "CASE076",
        "name": "Road Traffic Accident",
        "department_reference": "DEP015",
        "specialty_reference": "SP015",
        "diagnosis_reference": "DXEM001",
        "encounter": {
            "type": "Emergency",
            "visit_reason": "Emergency Visit",
            "chief_complaint": "Trauma following a road traffic accident",
        },
        "clinical_history": "Polytrauma patient brought to ER, stabilized and managed",
        "medication_references": ['MED000001'],
        "observation_references": ['OBS000001', 'OBS000002', 'OBS000008'],
        "lab_references": ['LAB000001'],
        "procedure_references": ['PROC000004', 'PROC000002'],
        "vaccine_references": [],
        "document_types": ['Discharge Summary'],
        "billing_profile": "Emergency Medicine",
        "follow_up_interval_days": 7,
        "selection_weight": 2,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'MedicationRequest', 'Observation', 'DiagnosticReport', 'Procedure', 'DocumentReference'],
    },

    {
        "case_id": "CASE077",
        "name": "Acute Chest Pain",
        "department_reference": "DEP015",
        "specialty_reference": "SP015",
        "diagnosis_reference": "DXEM002",
        "encounter": {
            "type": "Emergency",
            "visit_reason": "Emergency Visit",
            "chief_complaint": "Sudden onset chest pain",
        },
        "clinical_history": "Chest pain evaluated in ER to rule out cardiac cause",
        "medication_references": [],
        "observation_references": ['OBS000001', 'OBS000002', 'OBS000008'],
        "lab_references": ['LAB000005'],
        "procedure_references": ['PROC000003'],
        "vaccine_references": [],
        "document_types": ['Discharge Summary'],
        "billing_profile": "Emergency Medicine",
        "follow_up_interval_days": 7,
        "selection_weight": 3,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'Observation', 'DiagnosticReport', 'Procedure', 'DocumentReference'],
    },

    {
        "case_id": "CASE078",
        "name": "Syncope",
        "department_reference": "DEP015",
        "specialty_reference": "SP015",
        "diagnosis_reference": "DXEM003",
        "encounter": {
            "type": "Emergency",
            "visit_reason": "Emergency Visit",
            "chief_complaint": "Sudden loss of consciousness",
        },
        "clinical_history": "Syncope evaluated in ER, vitals stabilized",
        "medication_references": [],
        "observation_references": ['OBS000001', 'OBS000002'],
        "lab_references": [],
        "procedure_references": ['PROC000003'],
        "vaccine_references": [],
        "document_types": ['Discharge Summary'],
        "billing_profile": "Emergency Medicine",
        "follow_up_interval_days": 14,
        "selection_weight": 2,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'Observation', 'Procedure', 'DocumentReference'],
    },

    {
        "case_id": "CASE079",
        "name": "Snake Bite",
        "department_reference": "DEP015",
        "specialty_reference": "SP015",
        "diagnosis_reference": "DXEM004",
        "encounter": {
            "type": "Emergency",
            "visit_reason": "Emergency Visit",
            "chief_complaint": "Snake bite with local swelling",
        },
        "clinical_history": "Snake bite case, observed and managed in ER",
        "medication_references": [],
        "observation_references": ['OBS000001', 'OBS000002'],
        "lab_references": ['LAB000001'],
        "procedure_references": ['PROC000004'],
        "vaccine_references": [],
        "document_types": ['Discharge Summary'],
        "billing_profile": "Emergency Medicine",
        "follow_up_interval_days": 7,
        "selection_weight": 1,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'Observation', 'DiagnosticReport', 'Procedure', 'DocumentReference'],
    },

    {
        "case_id": "CASE080",
        "name": "Heat Stroke",
        "department_reference": "DEP015",
        "specialty_reference": "SP015",
        "diagnosis_reference": "DXEM005",
        "encounter": {
            "type": "Emergency",
            "visit_reason": "Emergency Visit",
            "chief_complaint": "High fever and altered sensorium after sun exposure",
        },
        "clinical_history": "Heat stroke, managed with cooling and IV fluids in ER",
        "medication_references": [],
        "observation_references": ['OBS000004', 'OBS000001'],
        "lab_references": [],
        "procedure_references": ['PROC000004'],
        "vaccine_references": [],
        "document_types": ['Discharge Summary'],
        "billing_profile": "Emergency Medicine",
        "follow_up_interval_days": 7,
        "selection_weight": 1,
        "expected_fhir_resources": ['Patient', 'Practitioner', 'Organization', 'Encounter', 'Condition', 'Composition', 'Bundle', 'Observation', 'Procedure', 'DocumentReference'],
    },

]
