"""Auto-generated diagnosis master."""

GENERAL_MEDICINE = [
    {
        "diagnosis_reference": "DXGM001",
        "condition_name": "Essential Hypertension",
        "icd10": "I10",
        "snomed": "59621000",
        "department_reference": "DEP001",
        "chronic": True,
        "severity": "Mild",
    },
    {
        "diagnosis_reference": "DXGM002",
        "condition_name": "Type 2 Diabetes Mellitus",
        "icd10": "E11",
        "snomed": "44054006",
        "department_reference": "DEP001",
        "chronic": True,
        "severity": "Moderate",
    },
    {
        "diagnosis_reference": "DXGM003",
        "condition_name": "Acute Viral Fever",
        "icd10": "B34.9",
        "snomed": "34014006",
        "department_reference": "DEP001",
        "chronic": False,
        "severity": "Mild",
    },
    {
        "diagnosis_reference": "DXGM004",
        "condition_name": "Dengue Fever",
        "icd10": "A90",
        "snomed": "38362002",
        "department_reference": "DEP001",
        "chronic": False,
        "severity": "Moderate",
    },
    {
        "diagnosis_reference": "DXGM005",
        "condition_name": "Typhoid Fever",
        "icd10": "A01.0",
        "snomed": "4834000",
        "department_reference": "DEP001",
        "chronic": False,
        "severity": "Moderate",
    },
    {
        "diagnosis_reference": "DXGM006",
        "condition_name": "Acute Gastroenteritis",
        "icd10": "A09",
        "snomed": "69776003",
        "department_reference": "DEP001",
        "chronic": False,
        "severity": "Mild",
    },
    {
        "diagnosis_reference": "DXGM007",
        "condition_name": "Iron Deficiency Anemia",
        "icd10": "D50.9",
        "snomed": "87522002",
        "department_reference": "DEP001",
        "chronic": True,
        "severity": "Moderate",
    },
    {
        "diagnosis_reference": "DXGM008",
        "condition_name": "Hypothyroidism",
        "icd10": "E03.9",
        "snomed": "40930008",
        "department_reference": "DEP001",
        "chronic": True,
        "severity": "Mild",
    },
    {
        "diagnosis_reference": "DXGM009",
        "condition_name": "Vitamin D Deficiency",
        "icd10": "E55.9",
        "snomed": "34713006",
        "department_reference": "DEP001",
        "chronic": False,
        "severity": "Mild",
    },
    {
        "diagnosis_reference": "DXGM010",
        "condition_name": "Hyperlipidemia",
        "icd10": "E78.5",
        "snomed": "55822004",
        "department_reference": "DEP001",
        "chronic": True,
        "severity": "Moderate",
    },
]